version: '3.8'
services:
  jwat-restapi:
    container_name: jwat-restapi
    image: jwat-restapi
    build: .
    env_file:
      - ./docker-server.env
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    container_name: jwat-restapi-db
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - '5434:5432'
    volumes:
      - db-volume:/var/lib/postgresql/data
volumes:
  db-volume: