export const ORDER_PAYMENT_TYPE = {
    CREDIT_CARD: "CREDIT_CARD",
    DEBIT_CARD: "DEBIT_CARD",
    PAYPAL: "PAYPAL",
    CASH: "CASH"
}

export const ORDER_PAYMENT_TYPE_ARR = ["CREDIT_CARD", "DEBIT_CARD", "PAYPAL", "CASH"]

export const ORDER_STATUS = {
    PENDING: "PENDING",
    IN_TRANSIT: "IN_TRANSIT",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED"
}

export const ORDER_STATUS_ARR = ["PENDING", "IN_TRANSIT", "DELIVERED", "CANCELLED"]