export const ORDER_PAYMENT_TYPE = {
    CREDIT_CARD: "CREDIT_CARD",
    DEBIT_CARD: "DEBIT_CARD",
    PAYPAL: "PAYPAL",
    CASH: "CASH"
}

export const ORDER_STATUS = {
    PENDING: "PENDING",
    IN_TRANSIT: "IN_TRANSIT",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED"
}